"""add budgets and recurring system

Revision ID: 042d7df93555
Revises: c7ac81bd629c
Create Date: 2026-05-11 15:32:23.672669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042d7df93555'
down_revision: Union[str, Sequence[str], None] = 'c7ac81bd629c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('limit_amount', sa.Float(), nullable=False),
    sa.Column('spent_amount', sa.Float(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('limit_amount > 0', name='check_budget_limit_positive'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='check_budget_month_range'),
    sa.CheckConstraint('spent_amount >= 0', name='check_budget_spent_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'month', 'year', name='unique_budget_per_user_category_month')
    )
    op.create_index('idx_budgets_user_created', 'budgets', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_budgets_user_month_year', 'budgets', ['user_id', 'month', 'year'], unique=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('daily', 'weekly', 'monthly', 'yearly')", name='check_recurring_frequency'),
    sa.CheckConstraint("type IN ('income', 'expense')", name='check_recurring_type'),
    sa.CheckConstraint('amount > 0', name='check_recurring_amount_positive'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='check_recurring_date_range'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recurring_end_date', 'recurring_transactions', ['end_date', 'is_active'], unique=False)
    op.create_index('idx_recurring_next_run', 'recurring_transactions', ['is_active', 'last_generated_at'], unique=False)
    op.create_index('idx_recurring_user_active', 'recurring_transactions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_id'), 'recurring_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_is_active'), 'recurring_transactions', ['is_active'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_user_id'), 'recurring_transactions', ['user_id'], unique=False)
    op.create_table('budget_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budget_alerts_budget', 'budget_alerts', ['budget_id'], unique=False)
    op.create_index('idx_budget_alerts_resolved', 'budget_alerts', ['budget_id', 'is_resolved'], unique=False)
    op.create_index(op.f('ix_budget_alerts_budget_id'), 'budget_alerts', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_alerts_id'), 'budget_alerts', ['id'], unique=False)
    op.create_table('recurring_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_transaction_id', sa.Integer(), nullable=False),
    sa.Column('generated_transaction_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['recurring_transaction_id'], ['recurring_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recurring_logs_generated_at', 'recurring_logs', ['generated_at'], unique=False)
    op.create_index('idx_recurring_logs_recurring', 'recurring_logs', ['recurring_transaction_id'], unique=False)
    op.create_index('idx_recurring_logs_status', 'recurring_logs', ['status'], unique=False)
    op.create_index(op.f('ix_recurring_logs_id'), 'recurring_logs', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_logs_recurring_transaction_id'), 'recurring_logs', ['recurring_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_logs_recurring_transaction_id'), table_name='recurring_logs')
    op.drop_index(op.f('ix_recurring_logs_id'), table_name='recurring_logs')
    op.drop_index('idx_recurring_logs_status', table_name='recurring_logs')
    op.drop_index('idx_recurring_logs_recurring', table_name='recurring_logs')
    op.drop_index('idx_recurring_logs_generated_at', table_name='recurring_logs')
    op.drop_table('recurring_logs')
    op.drop_index(op.f('ix_budget_alerts_id'), table_name='budget_alerts')
    op.drop_index(op.f('ix_budget_alerts_budget_id'), table_name='budget_alerts')
    op.drop_index('idx_budget_alerts_resolved', table_name='budget_alerts')
    op.drop_index('idx_budget_alerts_budget', table_name='budget_alerts')
    op.drop_table('budget_alerts')
    op.drop_index(op.f('ix_recurring_transactions_user_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_is_active'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_id'), table_name='recurring_transactions')
    op.drop_index('idx_recurring_user_active', table_name='recurring_transactions')
    op.drop_index('idx_recurring_next_run', table_name='recurring_transactions')
    op.drop_index('idx_recurring_end_date', table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_index('idx_budgets_user_month_year', table_name='budgets')
    op.drop_index('idx_budgets_user_created', table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
