"""Analytics service layer.

Provides business logic for financial analytics and insights.
Aggregates data from multiple models to generate dashboards.
"""

from datetime import date, datetime, timedelta
from sqlalchemy.orm import Session

from app.schemas.analytics_schema import (
    CashflowData,
    SavingsTrend,
    SpendingHeatmap,
    FinancialScore,
    CategoryAnalysis,
    DashboardOverview
)
from app.utils.analytics_calculations import AnalyticsCalculator


class AnalyticsService:
    """Service for generating analytics and insights."""
    
    @staticmethod
    def get_cashflow_analysis(
        db: Session,
        user_id: int,
        start_date: date | None = None,
        end_date: date | None = None
    ) -> list[CashflowData]:
        """Get monthly income vs expense cashflow.
        
        Args:
            db: Database session
            user_id: User to analyze
            start_date: Analysis start (default: 3 months ago)
            end_date: Analysis end (default: today)
        
        Returns:
            List of monthly cashflow data
        """
        if not end_date:
            end_date = date.today()
        if not start_date:
            start_date = end_date - timedelta(days=90)
        
        data = AnalyticsCalculator.get_monthly_cashflow(db, user_id, start_date, end_date)
        
        month_names = [
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        ]
        
        return [
            CashflowData(
                month=item['month'],
                year=item['year'],
                month_name=month_names[int(item['month']) - 1],
                total_income=item['total_income'],
                total_expenses=item['total_expenses'],
                net_cashflow=item['net_cashflow'],
                transaction_count=0
            )
            for item in data
        ]
    
    @staticmethod
    def get_spending_heatmap(
        db: Session,
        user_id: int,
        start_date: date | None = None,
        end_date: date | None = None
    ) -> list[SpendingHeatmap]:
        """Get spending breakdown by category.
        
        Args:
            db: Database session
            user_id: User to analyze
            start_date: Analysis start (default: current month)
            end_date: Analysis end (default: today)
        
        Returns:
            List of category spending data
        """
        if not end_date:
            end_date = date.today()
        if not start_date:
            # First day of current month
            start_date = date(end_date.year, end_date.month, 1)
        
        data = AnalyticsCalculator.get_category_breakdown(
            db, user_id, start_date, end_date, transaction_type="expense"
        )
        
        # Determine trend (would need historical comparison for accuracy)
        return [
            SpendingHeatmap(
                category_id=item['category_id'],
                category_name=item['category_name'],
                total_spent=item['total'],
                transaction_count=item['count'],
                percentage_of_total=item['percentage'],
                average_transaction=item['average'],
                trend="stable"  # Could calculate from previous period
            )
            for item in data
        ]
    
    @staticmethod
    def get_financial_score(
        db: Session,
        user_id: int
    ) -> FinancialScore:
        """Get overall financial health score.
        
        Evaluates:
        - Savings rate (40%)
        - Expense stability (30%)
        - Budget adherence (20%)
        - Income stability (10%)
        
        Args:
            db: Database session
            user_id: User to score
        
        Returns:
            Financial score with component breakdown
        """
        score_data = AnalyticsCalculator.calculate_financial_score(db, user_id, period_months=3)
        
        # Narrative insights/recommendations are generated by the Ollama-backed AI endpoints.
        # This analytics score method returns only deterministic numeric scoring data.
        insights: list[str] = []
        recommendations: list[str] = []
        
        return FinancialScore(
            score=score_data['score'],
            savings_rate_score=score_data['savings_rate_score'],
            budget_adherence_score=score_data['budget_adherence_score'],
            expense_stability_score=score_data['expense_stability_score'],
            income_stability_score=score_data['income_stability_score'],
            insights=insights,
            recommendations=recommendations
        )
    
    @staticmethod
    def get_category_analysis(
        db: Session,
        user_id: int,
        category_id: int,
        start_date: date | None = None,
        end_date: date | None = None
    ) -> CategoryAnalysis:
        """Deep analysis of spending in a category.
        
        Args:
            db: Database session
            user_id: User to analyze
            category_id: Category to analyze
            start_date: Analysis start
            end_date: Analysis end
        
        Returns:
            Detailed category analysis
        """
        if not end_date:
            end_date = date.today()
        if not start_date:
            start_date = end_date - timedelta(days=90)
        
        # Get category name
        from app.models.category_models import Category
        category = db.query(Category).filter(Category.id == category_id).first()
        category_name = category.name if category else "Unknown"
        
        # Get spending data
        data = AnalyticsCalculator.get_category_breakdown(
            db, user_id, start_date, end_date, transaction_type="expense"
        )
        
        category_data = next((d for d in data if d['category_id'] == category_id), None)
        
        if not category_data:
            return CategoryAnalysis(
                category_id=category_id,
                category_name=category_name,
                total_spent=0,
                transaction_count=0,
                average_transaction=0,
                min_transaction=0,
                max_transaction=0,
                stddev=0,
                monthly_breakdown=[],
                trend="stable",
                budget_allocation=None
            )
        
        from app.models.expense_models import Expense
        from sqlalchemy import func, extract
        
        monthly_query = db.query(
            extract('month', Expense.date).label('month'),
            extract('year', Expense.date).label('year'),
            func.sum(Expense.amount).label('total')
        ).filter(
            Expense.user_id == user_id,
            Expense.category_id == category_id,
            Expense.date >= start_date,
            Expense.date <= end_date
        ).group_by('month', 'year')
        
        monthly_breakdown = [
            {'month': int(row.month), 'year': int(row.year), 'amount': float(row.total)}
            for row in monthly_query
        ]
        
        return CategoryAnalysis(
            category_id=category_id,
            category_name=category_name,
            total_spent=category_data['total'],
            transaction_count=category_data['count'],
            average_transaction=category_data['average'],
            min_transaction=0,  # Could calculate
            max_transaction=0,  # Could calculate
            stddev=0,  # Could calculate
            monthly_breakdown=monthly_breakdown,
            trend="stable",  # Could calculate from comparison
            budget_allocation=None
        )
    
    @staticmethod
    def get_dashboard_overview(
        db: Session,
        user_id: int,
        period: str = "monthly",
        start_date: date | None = None,
        end_date: date | None = None,
    ) -> DashboardOverview:
        """Get complete dashboard overview for user.
        
        Args:
            db: Database session
            user_id: User to analyze
            period: "monthly", "quarterly", "yearly", or "custom"
            start_date: Optional explicit start date for custom reporting
            end_date: Optional explicit end date for custom reporting
        
        Returns:
            Complete dashboard overview
        """
        today = date.today()
        
        # Set date range based on period or explicit range
        if start_date is not None and end_date is not None:
            pass
        elif period == "monthly":
            start_date = date(today.year, today.month, 1)
            end_date = today
        elif period == "quarterly":
            quarter = (today.month - 1) // 3 + 1
            start_month = (quarter - 1) * 3 + 1
            start_date = date(today.year, start_month, 1)
            end_date = today
        else:  # yearly or custom
            start_date = date(today.year, 1, 1)
            end_date = today
        
        # Calculate key metrics
        cashflow_data = AnalyticsCalculator.get_monthly_cashflow(db, user_id, start_date, end_date)
        
        total_income = sum(m['total_income'] for m in cashflow_data)
        total_expenses = sum(m['total_expenses'] for m in cashflow_data)
        net_savings = total_income - total_expenses
        savings_rate = (net_savings / total_income * 100) if total_income > 0 else 0
        
        # Get spending heatmap
        category_breakdown = AnalyticsService.get_spending_heatmap(db, user_id, start_date, end_date)
        top_categories = sorted(category_breakdown, key=lambda x: x.total_spent, reverse=True)[:5]
        
        # Get financial score
        financial_score = AnalyticsService.get_financial_score(db, user_id)
        
        # Calculate averages
        from app.models.expense_models import Expense
        from sqlalchemy import func
        from app.models.budget_models import Budget
        
        total_transactions_count = db.query(func.count(Expense.id)).filter(
            Expense.user_id == user_id,
            Expense.date >= start_date,
            Expense.date <= end_date
        ).scalar() or 0
        
        days = max((end_date - start_date).days, 1)
        average_daily_spending = total_expenses / days if days > 0 else 0
        average_transaction = total_expenses / total_transactions_count if total_transactions_count > 0 else 0
        
        # Calculate budgets analysis
        budgets = db.query(Budget).filter(Budget.user_id == user_id).all()
        period_budgets = []
        start_month_date = start_date.replace(day=1)
        for b in budgets:
            try:
                b_date = date(b.year, b.month, 1)
                if start_month_date <= b_date <= end_date:
                    period_budgets.append(b)
            except ValueError:
                pass
                
        budgets_met = 0
        budgets_exceeded = 0
        total_limit = 0
        total_spent = 0
        for b in period_budgets:
            total_limit += b.limit_amount
            total_spent += b.spent_amount
            if b.spent_amount > b.limit_amount:
                budgets_exceeded += 1
            else:
                budgets_met += 1
                
        budget_utilization_percentage = (total_spent / total_limit * 100) if total_limit > 0 else 0
        
        return DashboardOverview(
            period=period,
            start_date=start_date,
            end_date=end_date,
            total_income=total_income,
            total_expenses=total_expenses,
            net_savings=net_savings,
            savings_rate=savings_rate,
            average_daily_spending=average_daily_spending,
            average_transaction_amount=average_transaction,
            total_transactions=total_transactions_count,
            expense_transactions=total_transactions_count,  # Could count expense vs income separately
            income_transactions=0,
            top_expense_categories=top_categories,
            top_income_sources=[],
            financial_score=financial_score,
            budgets_met=budgets_met,
            budgets_exceeded=budgets_exceeded,
            budget_utilization_percentage=budget_utilization_percentage
        )
    
    @staticmethod
    def get_savings_trends(
        db: Session,
        user_id: int,
        months: int = 12
    ) -> list[SavingsTrend]:
        """Get savings trends over time.
        
        Args:
            db: Database session
            user_id: User to analyze
            months: Number of months to include
        
        Returns:
            List of monthly savings trends
        """
        end_date = date.today()
        start_date = end_date - timedelta(days=months * 30)
        
        cashflow_data = AnalyticsCalculator.get_monthly_cashflow(db, user_id, start_date, end_date)
        
        month_names = [
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        ]
        
        cumulative_savings = 0
        trends = []
        
        for item in cashflow_data:
            savings = item['net_cashflow']
            cumulative_savings += savings
            savings_rate = (savings / item['total_income'] * 100) if item['total_income'] > 0 else 0
            
            trends.append(SavingsTrend(
                month=item['month'],
                year=item['year'],
                month_name=month_names[int(item['month']) - 1],
                savings=savings,
                savings_rate=savings_rate,
                cumulative_savings=cumulative_savings
            ))
        
        return trends
